name: Fetch Data from sheetDB

on:
  push:
    branches: [master]
  schedule:
    - cron: '0 */4 * * *'  # Runs every hour

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Requests
        run: pip install requests

      - name: Run Script to Fetch Data
        env:
          SHEETDB_AUTH: ${{ secrets.SHEETDB_AUTH }}
        run: |
          python fetch_data.py

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add public/data.json
          git commit -m "Update data from SheetDB" || echo "No changes"
          git push
