name: Fetch Data from SHEETDB

on:
  push:
    branches: [master]
  schedule:
    - cron: '0 */4 * * *' # Every 4 hours

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: pip install requests

      - name: Run Python Script
        env:
          SHEETDB_AUTH: ${{ secrets.SHEETDB_AUTH }}
        run: |
          echo "Running fetch_data.py..."
          python fetch_data.py

      - name: Commit and Push if Changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add data.json
          git diff --quiet && git diff --staged --quiet || git commit -m "Update data from SheetDB"
          git push
